=== tonnarough/epam_training_task2/src/main/resources/appliances.xsd
<?xml version="1.0" encoding="UTF-8"?>
<sx:schema xmlns:sx="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.epam.by/appliance"
           xmlns:tns="http://www.epam.by/appliance">

    <sx:element name = "appliances">
        <sx:complexType>
            <sx:sequence>
                <sx:element name = "oven" type = "tns:Oven" minOccurs = "1"
                            maxOccurs = "unbounded"/>

                <sx:element name = "laptop" type = "tns:Laptop" minOccurs = "1"
                            maxOccurs = "unbounded"/>

                <sx:element name = "refrigerator" type = "tns:Refrigerator" minOccurs = "1"
                            maxOccurs = "unbounded"/>

                <sx:element name = "speakers" type = "tns:Speakers" minOccurs = "1"
                            maxOccurs = "unbounded"/>

                <sx:element name = "tabletPC" type = "tns:TablePC" minOccurs = "1"
                            maxOccurs = "unbounded"/>

                <sx:element name = "vacuumCleaner" type = "tns:VacuumCleaner" minOccurs = "1"
                            maxOccurs = "unbounded"/>
            </sx:sequence>
        </sx:complexType>
    </sx:element>

    <sx:complexType name="Oven">
        <sx:sequence>
            <sx:element name = "power_consumption" type = "sx:double" />
            <sx:element name = "weight" type = "sx:double" />
            <sx:element name = "capacity" type = "sx:double" />
            <sx:element name = "depth" type = "sx:double" />
            <sx:element name = "height" type = "sx:double" />
            <sx:element name = "width" type = "sx:double" />
        </sx:sequence>
        <sx:attribute name = "id" type = "sx:int" use = "required"/>
    </sx:complexType>

    <sx:complexType name="Laptop">
        <sx:sequence>
            <sx:element name = "battery_capacity" type = "sx:double" />
            <sx:element name = "os" type = "sx:string" />
            <sx:element name = "memory_rom" type = "sx:double" />
            <sx:element name = "system_memory" type = "sx:double" />
            <sx:element name = "cpu" type = "sx:double" />
            <sx:element name = "display_inchs" type = "sx:double" />
        </sx:sequence>
        <sx:attribute name = "id" type = "sx:int" use = "required"/>
    </sx:complexType>

    <sx:complexType name="Refrigerator">
        <sx:sequence>
            <sx:element name = "power_consumption" type = "sx:double" />
            <sx:element name = "weight" type = "sx:double" />
            <sx:element name = "freezer_capacity" type = "sx:double" />
            <sx:element name = "overall_capacity" type = "sx:double" />
            <sx:element name = "height" type = "sx:double" />
            <sx:element name = "width" type = "sx:double" />
        </sx:sequence>
        <sx:attribute name = "id" type = "sx:int" use = "required"/>
    </sx:complexType>

    <sx:complexType name="Speakers">
        <sx:sequence>
            <sx:element name = "power_consumption" type = "sx:double" />
            <sx:element name = "number_of_speakers" type = "sx:double" />
            <sx:element name = "frequency_range" type = "sx:string" />
            <sx:element name = "cord_length" type = "sx:double" />
        </sx:sequence>
        <sx:attribute name = "id" type = "sx:int" use = "required"/>
    </sx:complexType>

    <sx:complexType name="TablePC">
        <sx:sequence>
            <sx:element name = "battery_capacity" type = "sx:double" />
            <sx:element name = "display_inches" type = "sx:double" />
            <sx:element name = "memory_rom" type = "sx:double" />
            <sx:element name = "flash_memory_capacity" type = "sx:double" />
            <sx:element name = "color" type = "sx:string" />
        </sx:sequence>
        <sx:attribute name = "id" type = "sx:int" use = "required"/>
    </sx:complexType>

    <sx:complexType name="VacuumCleaner">
        <sx:sequence>
            <sx:element name = "power_consumption" type = "sx:double" />
            <sx:element name = "filter_type" type = "sx:string" />
            <sx:element name = "bag_type" type = "sx:string" />
            <sx:element name = "wand_type" type = "sx:string" />
            <sx:element name = "motor_speed_regulation" type = "sx:double" />
            <sx:element name = "cleaning_width" type = "sx:double" />
        </sx:sequence>
        <sx:attribute name = "id" type = "sx:int" use = "required"/>
    </sx:complexType>

</sx:schema>

=== tonnarough/epam_training_task2/src/main/resources/appliances.xml
<?xml version="1.0" encoding="UTF-8"?>
<x:appliances    xmlns:x = "http://www.epam.by/appliance"
                 xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation = "http://www.epam.by/appliance appliances.xsd">

    <oven id="1">
        <power_consumption>1000</power_consumption>
        <weight>10</weight>
        <capacity>32</capacity>
        <depth>60</depth>
        <height>45.5</height>
        <width>59.5</width>
    </oven>

    <oven id="2">
        <power_consumption>1500</power_consumption>
        <weight>12</weight>
        <capacity>33</capacity>
        <depth>60</depth>
        <height>45</height>
        <width>68</width>
    </oven>

    <oven id="3">
        <power_consumption>2000</power_consumption>
        <weight>11</weight>
        <capacity>33</capacity>
        <depth>60</depth>
        <height>40</height>
        <width>70</width>
    </oven>

    <laptop id = "1">
        <battery_capacity>1</battery_capacity>
        <os>Windows</os>
        <memory_rom>4000</memory_rom>
        <system_memory>1000</system_memory>
        <cpu>1.2</cpu>
        <display_inchs>18</display_inchs>
    </laptop>

    <laptop id = "2">
        <battery_capacity>1.5</battery_capacity>
        <os>Linux</os>
        <memory_rom>8000</memory_rom>
        <system_memory>1000</system_memory>
        <cpu>2.2</cpu>
        <display_inchs>19</display_inchs>
    </laptop>

    <laptop id = "3">
        <battery_capacity>3</battery_capacity>
        <os>Windows</os>
        <memory_rom>8000</memory_rom>
        <system_memory>1500</system_memory>
        <cpu>3.2</cpu>
        <display_inchs>22</display_inchs>
    </laptop>

    <refrigerator  id = "1">
        <power_consumption>100</power_consumption>
        <weight>20</weight>
        <freezer_capacity>10</freezer_capacity>
        <overall_capacity>300</overall_capacity>
        <height>200</height>
        <width>70</width>
    </refrigerator >

    <refrigerator  id = "2">
        <power_consumption>200</power_consumption>
        <weight>30</weight>
        <freezer_capacity>15</freezer_capacity>
        <overall_capacity>300</overall_capacity>
        <height>180</height>
        <width>80</width>
    </refrigerator >

    <refrigerator  id = "3">
        <power_consumption>150</power_consumption>
        <weight>35</weight>
        <freezer_capacity>20</freezer_capacity>
        <overall_capacity>350.5</overall_capacity>
        <height>250</height>
        <width>75</width>
    </refrigerator >

    <speakers   id = "1">
        <power_consumption>15</power_consumption>
        <number_of_speakers>2</number_of_speakers>
        <frequency_range>2-4</frequency_range>
        <cord_length>2</cord_length>
    </speakers >

    <speakers   id = "2">
        <power_consumption>20</power_consumption>
        <number_of_speakers>3</number_of_speakers>
        <frequency_range>3-4</frequency_range>
        <cord_length>3</cord_length>
    </speakers >

    <speakers   id = "3">
        <power_consumption>17</power_consumption>
        <number_of_speakers>4</number_of_speakers>
        <frequency_range>2-3.5</frequency_range>
        <cord_length>4</cord_length>
    </speakers >

    <tabletPC   id = "1">
        <battery_capacity>3</battery_capacity>
        <display_inches>14</display_inches>
        <memory_rom>8000</memory_rom>
        <flash_memory_capacity>2</flash_memory_capacity>
        <color>blue</color>
    </tabletPC >

    <tabletPC   id = "2">
        <battery_capacity>4</battery_capacity>
        <display_inches>15</display_inches>
        <memory_rom>8000</memory_rom>
        <flash_memory_capacity>6</flash_memory_capacity>
        <color>red</color>
    </tabletPC  >

    <tabletPC   id = "3">
        <battery_capacity>5</battery_capacity>
        <display_inches>16</display_inches>
        <memory_rom>16000</memory_rom>
        <flash_memory_capacity>8</flash_memory_capacity>
        <color>green</color>
    </tabletPC  >

    <vacuumCleaner  id = "1">
        <power_consumption>100</power_consumption>
        <filter_type>A</filter_type>
        <bag_type>A2</bag_type>
        <wand_type>all-in-one</wand_type>
        <motor_speed_regulation>3000</motor_speed_regulation>
        <cleaning_width>20</cleaning_width>
    </vacuumCleaner >

    <vacuumCleaner  id = "2">
        <power_consumption>110</power_consumption>
        <filter_type>B</filter_type>
        <bag_type>AA-89</bag_type>
        <wand_type>all-in-one</wand_type>
        <motor_speed_regulation>2900</motor_speed_regulation>
        <cleaning_width>25</cleaning_width>
    </vacuumCleaner >

    <vacuumCleaner  id = "3">
        <power_consumption>90</power_consumption>
        <filter_type>C</filter_type>
        <bag_type>XX00</bag_type>
        <wand_type>all-in-one</wand_type>
        <motor_speed_regulation>2950</motor_speed_regulation>
        <cleaning_width>30</cleaning_width>
    </vacuumCleaner >
</x:appliances>
